{ homeName }:

[
    ../../../../home/${homeName}/gnome/tweaks.nix
    ../../../../home/${homeName}/gnome/console.nix
    ../../../../home/${homeName}/gnome/gtk.nix
    ../../../../home/${homeName}/gnome/config.nix
    ../../../../home/${homeName}/gnome/input/touchpad.nix
    ../../../../home/${homeName}/gnome/input/keyboard.nix
    ../../../../home/${homeName}/gnome/extensions/dash-to-dock.nix
    ../../../../home/${homeName}/gnome/extensions/gesture-improvements.nix
    ../../../../home/${homeName}/gnome/extensions/just-perfection.nix
    ../../../../home/${homeName}/gnome/extensions/tray-icons-reloaded.nix
    ../../../../home/${homeName}/desktop/defaultApps.nix
    ../../../../home/${homeName}/desktop/userDirs.nix

    ../../../../home/${homeName}/applications/chromium.nix
    ../../../../home/${homeName}/applications/dev.nix
    ../../../../home/${homeName}/applications/evolution.nix
    ../../../../home/${homeName}/applications/firefox.nix
    ../../../../home/${homeName}/applications/fzf.nix
    ../../../../home/${homeName}/applications/node.nix
    ../../../../home/${homeName}/applications/git.nix
    ../../../../home/${homeName}/applications/gnome.nix
    ../../../../home/${homeName}/applications/gpg.nix
    ../../../../home/${homeName}/applications/htop.nix
    ../../../../home/${homeName}/applications/neovim.nix
    ../../../../home/${homeName}/applications/openssh.nix
    ../../../../home/${homeName}/applications/vscode.nix
    ../../../../home/${homeName}/applications/wsu2fa.nix
    ../../../../home/${homeName}/applications/zsh.nix
    ../../../../home/${homeName}/applications/steam.nix
    ../../../../home/${homeName}/applications/polymc.nix
    ../../../../home/${homeName}/applications/discord.nix
    ../../../../home/${homeName}/applications/setzer.nix
    ../../../../home/${homeName}/applications/bitwarden.nix
    ../../../../home/${homeName}/applications/nix.nix
    ../../../../home/${homeName}/applications/virt.nix
    ../../../../home/${homeName}/applications/direnv.nix
    ../../../../home/${homeName}/applications/helvum.nix
    ../../../../home/${homeName}/applications/helix
]
