[
    ../../../config/virt.nix
    ../../../config/users.nix
    ../../../config/time.nix
    ../../../config/console.nix
    ../../../config/sudo.nix
    ../../../config/printing.nix
    ../../../config/pam.nix
    ../../../config/nix.nix
    ../../../config/kernel.nix
    ./kernel.nix
    ../../../config/fonts.nix
    ../../../config/boot.nix
    ../../../config/audio.nix
    ../../../config/acpi.nix
    ../../../config/networking/general.nix
    ./networking.nix
    ../../../config/networking/dispatcherScripts/captivePortal.nix
    ../../../config/networking/openssh.nix
    ../../../config/networking/firewall/fail2ban.nix
    ../../../config/networking/firewall/nftables.nix
    ./firewall/nftables.nix
    ../../../config/networking/vpn/wireguard.nix
    ../../../config/hardware/tpm.nix
#    ./nvidia.nix
    ../../../config/hardware/keyboard.nix
    ../../../config/hardware/gpu.nix
    ../../../config/hardware/battery.nix
    ./gpu.nix
    ../../../config/de/gnome.nix
    ../../../config/cpu/intel.nix
    ../../../config/fs/mounts.nix
    ./mounts.nix
    ./lid.nix
    ./virt.nix
    ../../../config/ld.nix
    ../../../config/env.nix
    ../../../config/docs.nix
    ../../../config/tailscale.nix

    ../../../config/applications/steam.nix
    ../../../config/applications/python.nix
    ../../../config/applications/nodejs.nix
    ../../../config/applications/java.nix
    ../../../config/applications/evolution.nix
    ../../../config/applications/general.nix
]
