builtins.map (path: ../../../home/${path}) [
    "env.nix"

    "dev/c.nix"
    "dev/rust.nix"
    "dev/node.nix"
    "dev/python.nix"
    "dev/java"
    "dev/gradle.nix"
    "dev/dotnet.nix"
    "dev/prettier.nix"
    "dev/editor-config.nix"

    "applications/tools.nix"
    "applications/fzf.nix"
    "applications/git.nix"
    "applications/gpg.nix"
    "applications/htop.nix"
    "applications/openssh.nix"
    "applications/zsh"
    "applications/vscode/server.nix"
    "applications/direnv.nix"
    "applications/helix"
    "applications/bat.nix"
    "applications/nix.nix"
    "applications/podman.nix"
    "applications/wget.nix"
]
