[
    ../../../config/users.nix
    ../../../config/time.nix
    ../../../config/console.nix
    ../../../config/sudo.nix
    ../../../config/pam.nix
    ../../../config/nix.nix
    ../../../config/kernel.nix
    ../../../config/fonts.nix
    ../../../config/boot.nix
    ../../../config/networking/general.nix
    ../../../config/networking/openssh.nix
    ../../../config/hardware/keyboard.nix
    ../../../config/hardware/hyperv.nix
    ../../../config/de/gnome.nix
    ./gnome.nix
    ../../../config/fs/mounts.nix
    ./mounts.nix
    ../../../config/env.nix
    ../../../config/docs.nix
    ../../../config/pam-mount.nix
    ../../../config/lvm.nix
    ../../../config/systemd/config.nix

    ../../../config/applications/general.nix
]
