[
    ../../../config/virt.nix
    ../../../config/users.nix
    ../../../config/time.nix
    ../../../config/console.nix
    ../../../config/sudo.nix
    ../../../config/pam.nix
    ../../../config/nix.nix
    ../../../config/kernel.nix
    ../../../config/fonts.nix
    ../../../config/boot.nix
    ../../../config/audio.nix
    ../../../config/networking/general.nix
    ../../../config/networking/dispatcherScripts.nix
    ../../../config/networking/openssh.nix
    ../../../config/networking/firewall/fail2ban.nix
    ../../../config/networking/firewall/nftables.nix
    ./firewall/nftables.nix
    ../../../config/hardware/keyboard.nix
    ../../../config/hardware/hyperv.nix
    ../../../config/de/gnome.nix
    ../../../config/fs/mounts.nix
    ./mounts.nix

    ../../../config/applications/steam.nix
    ../../../config/applications/python.nix
    ../../../config/applications/nodejs.nix
    ../../../config/applications/java.nix
    ../../../config/applications/evolution.nix
    ../../../config/applications/general.nix
]