name: Build Installer Image

on:
  push:
    branches: [main]

jobs:
  build-installer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix build .#generators.install-iso.installer

      - uses: actions/upload-artifact@v4
        with:
          name: installer-iso
          path: ./result/iso/*
          compression-level: 0
