name: Update Nix Inputs

on:
  push:
    branches: [main]

jobs:
  update-inputs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - run: nix run .#test
